### ISSUE TITLE
faker-cli should be a separate gem

### ISSUE THREAD

**Issue by vbrazo** [faker-ruby/faker-cli#2]
## Checklist
- [x] Invite @akabiru  to be collaborator of this repository
- [ ] Publish `faker-cli` as a separate gem
- [ ] Grant admin access to @stympy on Rubygems.org

**Comment by akabiru** [comment]
Thanks @vbrazo , I'm at hand to assist in the migration. I think we can port [fakerbot](https://github.com/akabiru/fakerbot) as is here and migrate the issues raised on [faker](https://github.com/stympy/faker)

**Comment by akabiru** [comment]
> Thanks @vbrazo , I'm at hand to assist in the migration. I think we can port [fakerbot](https://github.com/akabiru/fakerbot) as is here and migrate the issues raised on [faker](https://github.com/stympy/faker)

My mistake, It's already done cheers! 😎

**Comment by akabiru** [comment]
We just need to update the namespaces from `FakerBot` to `Faker::CLI` I can get started on that.

**Comment by vbrazo** [comment]
Thanks for the support @akabiru I'm inviting you as a collaborator for this repository.
